config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('plataforma.urls')),
    path('Usuarios/',include('usuarios.urls')),
    path('AtencionPoblacion/',include('atencion_poblacion.urls')),
    # Sección Notificaciones
    path('Notificaciones/',include('notificaciones.urls')),
    path('SecretariaDocente/', include('secretaria_docente.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secretaria_docente/urls.py
from django.urls import path
from. import views
from django.contrib.auth.decorators import login_required
from .views import (
    Main,
    Tramites_All,
    Tramites_Delete_Tramites_All,
    Sitio_Administrativo,
    Cambiar_Gestor,
    Gestores,
    Graficas,
    Cambiar_Estado,
    Tramites_Detail_Admin,
    Tramites_Tipo_Pregrado,
    Tramites_Delete_Tramites_Tipo_Pregrado,
    Tramites_Tipo_Posgrado,
    Tramites_Delete_Tramites_Tipo_Posgrado,
    Tramites_Detail_Posgrado,
    Tramites_Detail_Pregrado,
)
from .views_tramites import (
    Tramites_Anonymous,
    Tramites_List,
    Tramites_Delete_User,
    Tramites_Detail,
    Tramites_Pregrado_Nacional_Create,
    Tramites_Usuario,
    Tramites_Detail_Usuario,

    Pregrado_Nacional_Legalizacion,
    Tramites_Pregrado_Internacional_Create,
    Pregrado_Internacional_Legalizacion,

    Tramites_Posgrado_Nacional_Create,
    Tramite_Posgrado_Nacional_Create_Legalizacion,
    Tramite_Posgrado_Internacional_Create,
    Tramite_Posgrado_Internacional_Legalizacion, 
)

from .api import TramiteViewSet
from rest_framework import routers

router =  routers.DefaultRouter()
router.register('api/Tramite', TramiteViewSet, 'Tramite')

urlpatterns = [
    # TRAMITES
    path('Secretaria/', Main, name="Secretaria"),
    path('Tramites_List/', Tramites_List.as_view(), name="Tramites_List"),
    path('Tramites_Delete_User/<int:id>/', Tramites_Delete_User, name="Tramites_Delete_User"),
    path('Tramites_Detail/<int:pk>/', Tramites_Detail.as_view(), name="Tramites_Detail"),
    
    #Usuarios Anonimos
    path('Tramites_Anonymous/', Tramites_Anonymous, name='Tramites_Anonymous'),

    #Usuarios Autenticados
    path('Tramites_Usuario/', Tramites_Usuario, name="Tramites_Usuario"),
     path('Tramites_Detail_Usuario/<int:pk>/', Tramites_Detail_Usuario.as_view(), name="Tramites_Detail_Usuario"),
    
    # PREGRADO NACIONAL 
    path('Tramites_Pregrado_Nacional_Create/',  Tramites_Pregrado_Nacional_Create.as_view(), name="Tramites_Pregrado_Nacional_Create"),
    path('Pregrado_Nacional_Legalizacion/', Pregrado_Nacional_Legalizacion.as_view(), name='Pregrado_Nacional_Legalizacion'),
 
   
    # PREGRADO INTERNACIONAL
    path('Tramites_Pregrado_Internacional_Create/', Tramites_Pregrado_Internacional_Create, name='Tramites_Pregrado_Internacional_Create'),
    path('Pregrado_Internacional_Legalizacion/', Pregrado_Internacional_Legalizacion.as_view(), name='Pregrado_Internacional_Legalizacion'),
    


    # POSGRADO NACIONAL
    path('Tramites_Posgrado_Nacional_Create/', Tramites_Posgrado_Nacional_Create.as_view(), name="Tramites_Posgrado_Nacional_Create"),
    path('Tramite_Posgrado_Nacional_Create_Legalizacion/', Tramite_Posgrado_Nacional_Create_Legalizacion.as_view(), name="Tramite_Posgrado_Nacional_Create_Legalizacion"),
    
    # POSGRADO INTERNACIONAL  
    path('Tramite_Posgrado_Internacional_Create/', Tramite_Posgrado_Internacional_Create.as_view(), name="Tramite_Posgrado_Internacional_Create"),
    path('Tramite_Posgrado_Internacional_Legalizacion/', Tramite_Posgrado_Internacional_Legalizacion.as_view(), name="Tramite_Posgrado_Internacional_Legalizacion"),

    
     # Admin
    path('Sitio_Administrativo/', login_required(Sitio_Administrativo), name="Sitio_Administrativo"),
    path('Cambiar_Gestor/<int:id>/', login_required(Cambiar_Gestor), name="Cambiar_Gestor"),
    path('Gestores/',login_required(Gestores), name="Gestores"),
    path('Graficas/', login_required(Graficas), name="Graficas"),
    path('Cambiar_Estado/<int:id>/',login_required(Cambiar_Estado), name="Cambiar_Estado"),
    path('Tramites_All/', Tramites_All.as_view(), name="Tramites_All"),
    path('Tramites_Delete_Tramites_All/<int:id>/', Tramites_Delete_Tramites_All, name="Tramites_Delete_Tramites_All"),
    path('Tramites_Tipo_Pregrado/', Tramites_Tipo_Pregrado, name='Tramites_Tipo_Pregrado'),
    path('Tramites_Delete_Tramites_Tipo_Pregrado/<int:id>/', Tramites_Delete_Tramites_Tipo_Pregrado, name='Tramites_Delete_Tramites_Tipo_Pregrado'),
    path('Tramites_Tipo_Posgrado/', Tramites_Tipo_Posgrado, name='Tramites_Tipo_Posgrado'),
    path('Tramites_Delete_Tramites_Tipo_Posgrado/<int:id>/', Tramites_Delete_Tramites_Tipo_Posgrado, name='Tramites_Delete_Tramites_Tipo_Posgrado'),

    path('Tramites_Detail_Posgrado/<int:pk>/', Tramites_Detail_Posgrado.as_view(), name="Tramites_Detail_Posgrado"),
    path('Tramites_Detail_Pregrado/<int:pk>/', Tramites_Detail_Pregrado.as_view(), name="Tramites_Detail_Pregrado"),

    path('Tramites_Detail_Admin/<int:pk>/', Tramites_Detail_Admin.as_view(), name="Tramites_Detail_Admin"),
    path('Informacion_Usuario/<int:id>/',login_required (views.Informacion_Usuario), name="Informacion_Usuario"),
]

urlpatterns = urlpatterns + router.urls  

secretaria_docente/models.py
from django.conf import settings
from django.db import models
from plataforma.models import TramiteGeneral
from usuarios.models import Usuario
import uuid
from .choices import (
    Intereses,
    Programa_Academico,
    Estado,
    Year,
    Organismo,
    Carrera,
    Tipo_Estudio,
    Tipo_Est,
    Uso,
    Uso_i,
    Tipo_Tramite_PreN,
    Tipo_Tramite_PreI,
    Tipo_Tramite_PosN,
    Tipo_Tramite_PosI,
    )

# Create your models here.


# Tramites
class Tramite(TramiteGeneral):
    numero_seguimiento = models.CharField(max_length=36, blank=True)
    tipo_estudio = models.CharField(max_length=50, choices=Tipo_Estudio, default = "" )
    tipo_est = models.CharField(max_length=50, choices=Tipo_Est, default = "" )
    uso = models.CharField( max_length=50, choices= Uso, default = "" )
    uso_i = models.CharField( max_length=50,choices= Uso_i, default = "" )
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, blank=True, null=True)
    nombre = models.CharField(max_length = 150, blank=False, null=False)
    apellidos = models.CharField(max_length = 150, blank=False, null=False)
    ci = models.CharField(max_length = 11, blank=False, null=False)
    email = models.EmailField(max_length = 50, blank=False, null=False)
    telefono = models.CharField(max_length = 8, blank=False, null=False)
    tomo = models.CharField(max_length = 4, blank=False,null= False)
    folio = models.CharField(max_length = 4, blank=False,null= False)
    numero = models.CharField(max_length = 4, blank=False,null= False)
    fecha = models.DateField(blank=False, null=False, auto_now=True)
    estado = models.CharField(max_length = 100, blank=False, null=False, choices = Estado, default = "En Espera")
   
    intereses = models.CharField(max_length = 250, blank=False, null=False, choices=Intereses, default="Estatal")
    organismo = models.CharField(max_length = 150, blank=True, null=True)
    organismo_op = models.CharField(max_length = 250, choices= Organismo, default = "" )
    motivo = models.CharField(max_length = 250, blank=True, null=True)
    funcionario = models.CharField(max_length=50)
    carrera = models.CharField(max_length=50, blank=False, null=False, choices = Carrera)
    year = models.CharField(max_length = 50, blank=False, null=False, choices= Year, default = 1)
    
    programa_academico = models.CharField(max_length = 250, blank=False, null=False, choices= Programa_Academico )
    nombre_programa =models.CharField(max_length = 250, blank=False, null=False)
    
    tipo_pren = models.CharField(max_length=50, blank=False, null=False, choices = Tipo_Tramite_PreN)
    tipo_prei = models.CharField(max_length=50, blank=False, null=False, choices = Tipo_Tramite_PreI)
    tipo_posn = models.CharField(max_length=50, blank=False, null=False, choices = Tipo_Tramite_PosN)
    tipo_posi = models.CharField(max_length=50, blank=False, null=False, choices = Tipo_Tramite_PosI)
    legalizacion = models.CharField(max_length=50, default='Legalización de Foto Copia de Título')
    
    archivo = models.FileField(upload_to='TramiteLegalizacion/' , null=False, blank=False)
    
    
    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.nombre_tramite = "Secretaría Docente"

    def __str__(self):
        return f"{self.ci} - {self.nombre}"
    

    class Meta:
        managed = True 
        

secretaria_docente/templates/Tramites/Pregrado/Int/tramite_pregrado_internacional_legalizacion.html
{% extends "navbar.html" %}
{% load static %}

  {% block css %}
    <link rel="stylesheet" href="{% static 'css/TramitesSD copy.css' %}">
  {% endblock %}


  {% block content %}
    <div class="content" >
      <div class="col">
        <div class="container-form">
          <div id="error-container">

          </div>
          <div class="form">
            <div class="container-fluid py-4">
              <div class="row">
                <div class="col-md-12">
                  <div class="card">
                    {% if messages %}
                      {% for message in messages %}
                        {% if message.tags == 'success' %}
                          <div style="position: absolute; right: 20px; top: 40px; display: flex; align-items: center; padding-right: 0rem; z-index: 2000;"
                              class="alert alert-success alert-dismissible fade show" role="alert">
                        {% elif message.tags == 'error' %}
                          <div style="position: absolute; right: 20px; top: 40px; display: flex; align-items: center; padding-right: 0rem; z-index: 2000; "
                              class="alert alert-danger alert-dismissible fade show" role="alert">
                        {% endif %}
                          {{ message }}
                            <button style="font-size: 10px; border-bottom: none; position: relative; box-shadow: none;" type="button"
                              class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                      {% endfor %}
                    {% endif %}
                    <div class="card-header pb-0">
                      <div class="title">
                        <h3 class="title-text p-3">Solicitud de Legalizaci&oacute;n de Fotocopia de T&iacute;tulo</h3>
                        <p class="text">
                            Por favor, complete todos los campos requeridos para enviar su solicitud.
                            Su informaci&oacute;n es vital para procesar su solicitud de manera adecuada y brindarle el mejor servicio posible.
                        </p>
                      </div>
                    </div>
                    <form  id="formu" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="card-body">
                        <h4 class="textt text-sm">Datos Generales</h4>
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="text-input" class="form-control-label">Nombre</label>
                              {{form.nombre}}
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="example-text-input" class="form-control-label">Apellidos</label>
                              {{form.apellidos}}
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="example-text-input" class="form-control-label">Carnet de Identidad</label>
                              {{form.ci}}
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="example-text-input" class="form-control-label">Correo Electr&oacute;nico</label>
                              {{form.email}}
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="example-text-input" class="form-control-label">N&uacute;mero de M&oacute;vil</label>
                              {{form.telefono}}
                            </div>
                          </div>
                        </div>
                        <hr class="horizontal dark">
                        <h4 class="textt text-sm">Datos de la Solicitud</h4>
                        <div class="row">
                          <div class="col-md-6 col-lg-4">
                            <div class="form-group select">
                              <label for="text-input" class="form-control-label">Tipo de Estudio</label>
                              {{form.tipo_estudio}}
                            </div>
                          </div>
                          <div class="col-md-6 col-lg-3">
                            <div class="form-group select">
                              <label for="text-input" class="form-control-label">Uso</label>
                              {{form.uso_i}} 
                            </div>
                          </div>
                          <div class="col-md-12 col-lg-5">
                            <div class="form-group select">
                              <label for="text-input" class="form-control-label">Fotocopia del T&iacute;tulo(Solo en PDF)</label>
                              {{form.archivo}}
                            </div>
                          </div>
                          <div class="form-group col-md-6 text-white" >
                            <label for="{{ form.intereses.id_for_label }}"  class="form-control-label"> Intereses</label>
                            <div style="display: flex; flex-wrap: wrap;" >
                              {% for id, label in form.intereses.field.choices %}
                              <div class="col-6">
                                <input class="form-check-input" type="radio" name="{{ form.intereses.html_name }}" id="{{ form.intereses.auto_id }}" value="{{ id }}" {% if form.data.intereses == id %}checked{% endif %}>
                                <label class="form-check-label form-control-label" for="{{ form.intereses.auto_id }}">{{ label }}</label>
                              </div>
                              {% endfor %}
                            </div>
                          </div>
                          <div id="prueba" style="display:none;" class="col-md-5 text-white">
                            <div class="form-group">
                              <label for="text-input" class="form-control-label">Organismo</label>
                              {{form.organismo_op}}
                            </div>
                          </div>
                          <div class="col-md-5" id="id_organismo" style="display:none;">
                            <div class="form-group">
                              <label for="text-input" class="form-control-label">Organismo</label>
                              {{form.organismo}}
                            </div>
                          </div>
                          <div class="col-md-12" id="id_motivo" style="display:none; ">
                            <div class="form-group">
                              <label for="text-input" class="form-control-label">Motivo</label>
                              {{form.motivo}}
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="text-input" class="form-control-label">Funcionario</label>
                              {{form.funcionario}}
                            </div>
                          </div>
                          <div class="col-md-4">
                            <div class="form-group">
                              <label for="text-input" class="form-control-label">Carrera</label>
                              {{form.carrera}}
                            </div>
                          </div>
                        <div class="col-md-4">
                          <div class="form-group">
                            <label for="text-input" class="form-control-label">Año</label>
                            {{form.year}}
                          </div>
                        </div>
                      </div>
                      <hr class="horizontal dark">
                      <h4 class="textt text-sm">Registro de T&iacute;tulos de la Secretar&iacute;a</h4>
                      <div class="row">
                        <div class="col-md-4">
                          <div class="form-group">
                            <label for="text-input" class="form-control-label">Tomo</label>
                            {{form.tomo}}
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="form-group">
                            <label for="text-input" class="form-control-label">Folio</label>
                            {{form.folio}}
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="form-group">
                            <label for="text-input" class="form-control-label">N&uacute;mero</label>
                            {{form.numero}}
                          </div>
                        </div>
                      </div>
                      <div class="boot d-flex flex-wrap justify-content-center align-items-center">
                        <input type="submit" value="Aceptar" id="boton" class="btn btn-primary btn-sm m-2">
                        <a href="{% url 'Secretaria' %}" class="btn btn-primary btn-sm m-2 text-decoration-none">Cancelar</a>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>    
      </div>
    </div>
  {% endblock %}
  
  {% block js %}

  <script src="{% static 'js/validations_pregrado_internacional_legalizacion.js' %}"></script>
  
  <script>
    // Define el nombre del campo de intereses como una variable global
  var interesesFieldName = "{{ intereses }}";
  
  document.addEventListener("DOMContentLoaded", function() {
    // Función para manejar el cambio en los radio buttons de Intereses
    function handleInterestChange() {
      
      var selectedInterest = document.querySelector(`input[id="id_intereses"]:checked`).value;
      var organismoOp = document.getElementById('prueba');
      var organismo = document.getElementById('id_organismo');
      var motivo = document.getElementById('id_motivo');
      console.log("selectedInterest")
      if (selectedInterest === 'Particular') {
        organismoOp.style = 'display:block;';
        organismo.style = 'display:none;';
        motivo.style = 'display:none;';
      } else if (selectedInterest === 'Estatal') {
        organismoOp.style = 'display:none;';
        organismo.style = 'display:block;';
        motivo.style = 'display:block;';
      }
    }
    
    document.querySelector("#id_intereses").checked = true

    handleInterestChange()
    
    // Actualiza los campos al cambiar la selección de Intereses
    document.querySelectorAll("#id_intereses").forEach(input => {
      input.addEventListener('change', handleInterestChange);
    });
    document.getElementById("formu").addEventListener("submit", function(e) {
      var selectedInterest = document.querySelector(`input[id="id_intereses"]:checked`).value;
      if (selectedInterest === 'Estatal') {
          var organismoField = document.getElementById('id_organismo').querySelector("input, select, textarea"); // Asume que el campo es un input, select o textarea
          var motivoField = document.getElementById('id_motivo').querySelector("input, select, textarea"); // Asume que el campo es un input, select o textarea
          if (!organismoField.value ||!motivoField.value) {
              e.preventDefault(); // Previene el envío del formulario
              organismoField.style = "border:solid 2px #212d57;"
              motivoField.style = "border:solid 2px #212d57;"
              alert('Los campos Organismo y Motivo son obligatorios cuando se selecciona Estatal.');
              // Aquí puedes agregar más lógica para mostrar mensajes de error específicos o resaltar los campos faltantes
          }
      }
  });

  });
</script>
 
  {% endblock %}